version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - YANDEX_MAPS_API_KEY=your-key
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=/api/
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
